name: mobile_aula_inteligente
description: "^Projecto para el segundo parcial"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  provider: ^6.1.5
  fl_chart: ^0.64.0
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  qr_flutter: ^4.0.0
  mobile_scanner: ^7.0.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
